version: "2"
services:

    nginx-proxy:
      build: ./build/nginx-proxy/
      container_name: nginx-proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./certs:/etc/nginx/certs

    pb-eazyshop:
      build: ./build/php7-laravel/
      container_name: pb-eazyshop
      volumes:
        - ../www/pb-eazyshop:/var/www/laravel
      links:
        - mysql
      environment:
        - VIRTUAL_HOST=local.pb-eazyshop.net,localadmin.pb-eazyshop.net

    # www-pb-eazyshop-maintain:
    #   image: php:5-apache
    #   container_name: www-pb-eazyshop-maintain
    #   volumes:
    #     - ../www/pb-eazyshop-maintain:/var/www/html
    #   environment:
    #     - VIRTUAL_HOST=www.pb-eazyshop.net
        
    # otakuman:
    #   image: wordpress
    #   container_name: otakuman
    #   volumes:
    #     - /home/otakuman/www:/var/www/html
    #   environment:
    #     WORDPRESS_DB_PASSWORD: AP17714500
    #     WORDPRESS_DB_HOST: db
    #     WORDPRESS_DB_USER: otakuman
    #     WORDPRESS_DB_PASSWORD: AP17714500
    #     WORDPRESS_DB_NAME: otakuman_wordpress
    #     VIRTUAL_HOST: otakuman.club
    #     VIRTUAL_HOST: www.otakuman.club
    #   links:
    #     - mysql:db


    # pb-eazyshop-old:
    #   build: ./build/php/
    #   container_name: pb-eazyshop-old
    #   volumes:
    #     - ../www/pb-eazyshop-old:/var/www/html
    #   links:
    #     - mysql:localhost
    #   environment:
    #     - VIRTUAL_HOST=old.pb-eazyshop.dev
    
    # comsci-alumni:
    #   image: eboraas/laravel
    #   container_name: comsci-alumni
    #   volumes:
    #     - ../www/comsci-alumni:/var/www/laravel
    #   links:
    #     - mysql
    #   environment:
    #     - VIRTUAL_HOST=comsci-alumni.dev

    # legendthbx-backend:
    #   build: ./build/laravel/
    #   container_name: legendthbx-backend
    #   volumes:
    #     - ../www/LegendThaiBoxing.Backend:/var/www/laravel
    #   links:
    #     - mysql
    #   environment:
    #     - VIRTUAL_HOST=legend.dev

    # feora:
    #   build: ./build/php7-laravel/
    #   container_name: feora
    #   volumes:
    #     - /d:/var/www/laravel
    #   links:
    #     - mysql
    #   environment:
    #     - VIRTUAL_HOST=feora.dev

    mysql:
      image: mysql
      container_name: mysql
      restart: always
      volumes:
        - ./build/mysql:/docker-entrypoint-initdb.d
        - ./tmp/mysql:/var/lib/mysql
      environment:
        MYSQL_DATABASE: "pb-eazyshop"
        MYSQL_USER: "pb-eazyshop"
        MYSQL_PASSWORD: "AP17714500"
        MYSQL_ROOT_PASSWORD: "AP17714500"
      ports:
        - "3306:3306"

    myadmin:
      container_name: myadmin
      image: phpmyadmin/phpmyadmin
      links:
        - mysql:db
      ports:
        - 8080:80
